web:
  build: ./showerNote/
  volumes:
    - "./showerNote:/src/app"
  ports:
    - "3030:3000"
  links:
    - "db:redis"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - web:web

db:
  image: redis:3.0
